"""Per-cell maximal conductances from Nicoletti et al. 2024, taken from the code.

    python tools/import_nicoletti2024_cells.py --fetch --out worm/neural/models/

Each cell's densities live in a bare vector ``g0`` in its driver. A comment above
it names the entries and **for three of seven cells that comment is wrong** --
VB6 names ten conductances for thirteen values, VD5 names ten for eight, and AIY
names ``irk`` where the code assigns ``shl1``. docs/model_assumptions.md 5I read
the comments, found them inconsistent, and concluded the mapping was unrecoverable.

It is recoverable, and it is not subtle. Each cell's voltage-clamp module assigns
the same vector into named NEURON mechanisms one index at a time:

    seg.slo1egl19.gbar = gVB6_scaled[0]
    seg.slo2egl19.gbar = gVB6_scaled[1]
    ...

That is executable, unambiguous, and it is what the published simulations ran. This
module reads *that* and uses the comments only to report disagreement. See 5W.

The scaling
-----------

``gScm2(g0, surf, k)`` divides the first ``k + 1`` entries by the cell's membrane
area to turn nS into S/cm^2, leaving reversal potentials and capacitances alone.
We invert nothing and convert nothing here: the published density and the surface
area are both recorded, so any later unit choice is made once, in the open, by the
code that builds a runtime. RIM is passed already in S/cm^2 and has no ``gScm2``
call, which is recorded as ``scaled = false`` rather than silently normalised.
"""

from __future__ import annotations

import argparse
import re
import sys
from dataclasses import dataclass
from pathlib import Path

from tools.assess_nicoletti2024 import COMMENT, GBAR, INDEX, VECTOR, drivers

SURFACE = re.compile(r"^\s*surf\s*=\s*([-\d.eE+]+)", re.MULTILINE)
CM = re.compile(r"soma\.cm\s*=\s*\w+\[(\d+)\]")


@dataclass(frozen=True)
class Cell:
    name: str
    surface_cm2: float | None
    conductances: tuple[tuple[str, float], ...]
    """``(mechanism, published value)`` in vector order, from the clamp driver."""
    tail: tuple[float, ...]
    """Entries after the last conductance: reversal potentials and capacitance."""
    scaled: bool
    comment_names: tuple[str, ...]

    @property
    def comment_agrees(self) -> bool:
        claimed = [n.lower() for n in self.comment_names[: len(self.conductances)]]
        return claimed == [m.lower() for m, _ in self.conductances]


def build(cell: str, driver: str, clamp: str) -> Cell | None:
    vector = VECTOR.search(driver)
    if not vector:
        return None
    values = [float(v) for v in vector.group(1).split(",") if v.strip()]

    mapping = sorted((int(i), mech) for mech, i in GBAR.findall(clamp))
    if not mapping:
        return None

    index = INDEX.search(driver)
    last = int(index.group(1)) if index else len(values) - 3
    if {i for i, _ in mapping} != set(range(last + 1)):
        return None

    surface = SURFACE.search(driver)
    comment = COMMENT.search(driver)
    return Cell(
        name=cell,
        surface_cm2=float(surface.group(1)) if surface else None,
        conductances=tuple((mech, values[i]) for i, mech in mapping),
        tail=tuple(values[last + 1 :]),
        scaled=index is not None,
        comment_names=tuple(n.strip() for n in comment.group(1).split(",") if n.strip())
        if comment
        else (),
    )


def to_toml(cell: Cell) -> str:
    out = [
        f"# {cell.name}, Nicoletti et al. 2024. Generated by",
        "# tools/import_nicoletti2024_cells.py from the published voltage-clamp",
        "# driver, NOT from the comment above the vector -- see",
        "# docs/model_assumptions.md 5W. Regenerate rather than editing.",
        "#",
        "# Nicoletti M, Chiodo L, Loppini A, Liu Q, Folli V, Ruocco G, Filippi S.",
        "# PLoS ONE 19(3):e0298105 (2024).",
        "",
        "[cell]",
        f'name = "{cell.name}"',
        f"surface_cm2 = {cell.surface_cm2!r}",
        "# Whether the published vector is divided by surface area before use.",
        f"scaled_by_surface = {str(cell.scaled).lower()}",
        "# Does the source comment agree with what the code assigns? Recorded",
        "# because for AIY, VB6 and VD5 it does not, and the code is the fact.",
        f"comment_agrees = {str(cell.comment_agrees).lower()}",
        "",
        "# Maximal conductances in vector order, as the clamp driver assigns them.",
        "[conductances]",
    ]
    for mechanism, value in cell.conductances:
        out.append(f"{mechanism} = {value!r}")
    out += [
        "",
        "# Entries after the last conductance: reversal potential(s) then",
        "# capacitance. Left unnamed because the source does not name them.",
        "[tail]",
        f"values = {list(cell.tail)!r}",
    ]
    return "\n".join(out) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.split(chr(10))[0])
    parser.add_argument("--fetch", action="store_true")
    parser.add_argument("--cache", type=Path, default=Path("build") / "nicoletti2024")
    parser.add_argument("--out", type=Path, default=None)
    args = parser.parse_args()

    found = drivers(args.cache, args.fetch)
    if not found:
        print(f"no drivers in {args.cache}; run with --fetch", file=sys.stderr)
        return 2

    by_cell: dict[str, Cell] = {}
    for name, text in found.items():
        cell = name.split("_")[0]
        if cell in by_cell or not VECTOR.search(text):
            continue
        clamp = next((b for o, b in found.items() if o.startswith(cell) and "vclamp" in o), "")
        built = build(cell, text, clamp)
        if built:
            by_cell[cell] = built

    for cell in sorted(by_cell.values(), key=lambda c: c.name):
        note = "" if cell.comment_agrees else "   COMMENT DISAGREES"
        print(
            f"{cell.name:6s} {len(cell.conductances):2d} conductances, "
            f"surface {cell.surface_cm2}, tail {len(cell.tail)}{note}"
        )
        if args.out:
            args.out.mkdir(parents=True, exist_ok=True)
            path = args.out / f"{cell.name.lower()}_nicoletti2024.toml"
            path.write_text(to_toml(cell), encoding="utf-8", newline="\n")
    if args.out:
        print(f"\nwrote {len(by_cell)} cells to {args.out}")
    return 0 if len(by_cell) == 7 else 1


if __name__ == "__main__":
    raise SystemExit(main())
